server.port=8088
spring.application.name=notification-service
spring.output.ansi.enabled= always
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
logging.level.root=ERROR

management.endpoints.web.exposure.include=prometheus
management.endpoint.prometheus.enabled=true