server.port=8761
spring.application.name=service-discovery
spring.output.ansi.enabled= always
eureka.instance.hostname=localhost

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.level.root=ERROR

management.endpoints.web.exposure.include=prometheus
management.endpoint.prometheus.enabled=true