# Application Name & Port
server:
  port: 8081

# Eureka Server Awakening
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: user-service
  output:
    ansi:
      enabled: always
  # H2 Database Settings
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/UserServiceDB?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

# JWT Secret Key
jwt:
  secret: ${JWT_SECRET_KEY}

logging:
  level:
    root: INFO


