# Application Name & Port
server:
  port: 8081

# Eureka Server Awakening
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: user-service
  output:
    ansi:
      enabled: always
  # H2 Database Settings
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:userdb
    driverClassName: org.h2.Driver
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# JWT Secret Key
jwt:
  secret: sollalullaviraiiilaawetatulhulevalapaaamhdddbhddddbhd

